# Generated by Django 6.0.2 on 2026-03-18 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("daily", "Дневной"),
                            ("weekly", "Недельный"),
                            ("monthly", "Месячный"),
                        ],
                        default="daily",
                        max_length=10,
                        verbose_name="Тип прогноза",
                    ),
                ),
                (
                    "period_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Период прогноза (дней)"
                    ),
                ),
                (
                    "predicted_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Прогнозируемая сумма",
                    ),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Нижняя граница (доверительный интервал)",
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Верхняя граница (доверительный интервал)",
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=95.0,
                        max_digits=5,
                        verbose_name="Уровень доверия (%)",
                    ),
                ),
                (
                    "model_version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Версия модели"
                    ),
                ),
                (
                    "training_data_points",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество точек обучения"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(verbose_name="Действителен до")),
                (
                    "is_actual",
                    models.BooleanField(default=True, verbose_name="Актуален"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогноз",
                "verbose_name_plural": "Прогнозы",
                "db_table": "forecasts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForecastDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "predicted_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Прогнозируемое значение",
                    ),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Нижняя граница",
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Верхняя граница",
                    ),
                ),
                (
                    "trend",
                    models.CharField(blank=True, max_length=20, verbose_name="Тренд"),
                ),
                (
                    "forecast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="analytics.forecast",
                        verbose_name="Прогноз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Деталь прогноза",
                "verbose_name_plural": "Детали прогноза",
                "db_table": "forecast_details",
                "ordering": ["date"],
            },
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["user", "forecast_type", "-created_at"],
                name="forecasts_user_id_cb18af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["user", "is_actual"], name="forecasts_user_id_5584e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="forecastdetail",
            index=models.Index(
                fields=["forecast", "date"], name="forecast_de_forecas_2fc9a5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="forecastdetail",
            unique_together={("forecast", "date")},
        ),
    ]
