# Generated by Django 6.0.2 on 2026-03-19 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        ("categories", "0002_create_system_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="forecast",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forecasts",
                to="categories.category",
                verbose_name="Категория (опционально)",
            ),
        ),
        migrations.AddIndex(
            model_name="forecast",
            index=models.Index(
                fields=["user", "category", "is_actual"],
                name="forecasts_user_id_b49273_idx",
            ),
        ),
    ]
