# Generated by Django 6.0.2 on 2026-02-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "type",
                    models.CharField(
                        choices=[("expense", "Расход"), ("income", "Доход")],
                        default="expense",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="default", help_text="Название иконки", max_length=50
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3498db", help_text="Цвет в формате HEX", max_length=7
                    ),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, help_text="Системная категория"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "db_table": "categories",
                "ordering": ["type", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "name", "type"), name="unique_user_category"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_system", True)),
                        fields=("name", "type"),
                        name="unique_system_category",
                    ),
                ],
            },
        ),
    ]
