# Generated by Django 6.0.2 on 2026-02-18 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Сумма"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("expense", "Расход"), ("income", "Доход")],
                        default="expense",
                        max_length=10,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("manual", "Вручную"), ("sms", "SMS")],
                        default="manual",
                        max_length=10,
                        verbose_name="Источник",
                    ),
                ),
                (
                    "is_ai_parsed",
                    models.BooleanField(default=False, verbose_name="Обработано AI"),
                ),
                ("date", models.DateTimeField(verbose_name="Дата")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="categories.category",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "db_table": "transactions",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "-date"], name="transaction_user_id_dff1f0_idx"
                    ),
                    models.Index(
                        fields=["user", "type", "-date"],
                        name="transaction_user_id_dd1053_idx",
                    ),
                ],
            },
        ),
    ]
