# Generated by Django 6.0.2 on 2026-02-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Аватар пользователя",
                null=True,
                upload_to="avatars/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Краткая информация о себе",
                max_length=500,
                null=True,
            ),
        ),
    ]
